baseURL = "/"
title = "AI Discovery - Your Ultimate AI Tools Guide"  
languageCode = "en-us"
enableRobotsTXT = true
enableGitInfo = false

[pagination]
  pagerSize = 12

[params]
  description = "Comprehensive reviews and guides for AI tools, productivity software, and intelligent automation solutions."
  author = "AI Discovery Team"
  keywords = "AI tools, artificial intelligence, productivity software, content creation AI, image generation, coding assistants"
  google_adsense_id = "ca-pub-test"
  google_analytics_id = "G-TEST"
  
  # SEO enhancements
  twitter = "@aidiscovery"
  github = "https://github.com/aidiscovery"
  linkedin = "https://linkedin.com/company/aidiscovery"
  email = "contact@aidiscovery.com"
  
  # Organization info for structured data
  organization_type = "Organization"
  founding_date = "2024"
  
  # Default sharing image
  default_image = "/images/ai-discovery-og.jpg"
  
  # Enable/disable features
  enable_breadcrumbs = true
  enable_structured_data = true
  enable_enhanced_seo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# Multilingual support
defaultContentLanguage = "en"
[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1
    title = "AI Discovery"
    [languages.en.params]
      description = "Your ultimate guide to AI tools and intelligent software"
  
  [languages.zh]
    contentDir = "content-zh" 
    languageName = "中文"
    weight = 2
    title = "AI工具发现"
    [languages.zh.params]
      description = "AI工具和智能软件的终极指南"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Content Creation"
    url = "/categories/content-creation/"
    weight = 2
  [[menu.main]]
    name = "Image Generation"
    url = "/categories/image-generation/"
    weight = 3
  [[menu.main]]
    name = "Code Assistance"
    url = "/categories/code-assistance/"
    weight = 4
  [[menu.main]]
    name = "Productivity"
    url = "/categories/productivity/"
    weight = 5

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# SEO and performance optimizations
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  
[minify.tdewolff.html]
  keepEndTags = false
  keepDefaultAttrVals = false
  keepDocumentTags = true
  keepWhitespace = false

[minify.tdewolff.css]
  keepCSS2 = true
  precision = 0

[minify.tdewolff.js]
  keepVarNames = false
  precision = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]